name: sbp_example
description: Demonstrates how to use the sbp plugin.

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sbp:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/source/
    - assets/source_png/
  uses-material-design: true
