name: sbp_example
description: Demonstrates how to use the sbp plugin.

environment:
  sdk: '>=2.16.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sbp:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/sbp/assets/sbp.png
    - packages/sbp/assets/icons/absolut.png
    - packages/sbp/assets/icons/akbars.png
    - packages/sbp/assets/icons/alfabank.png
    - packages/sbp/assets/icons/artsofte.png
    - packages/sbp/assets/icons/avangard.png
    - packages/sbp/assets/icons/bankuralsib.png
    - packages/sbp/assets/icons/bbr.png
    - packages/sbp/assets/icons/blanc.png
    - packages/sbp/assets/icons/brs.png
    - packages/sbp/assets/icons/bspb.png
    - packages/sbp/assets/icons/centrinvest.png
    - packages/sbp/assets/icons/elplat.png
    - packages/sbp/assets/icons/expobank.png
    - packages/sbp/assets/icons/factura.png
    - packages/sbp/assets/icons/gazprombank.png
    - packages/sbp/assets/icons/gebank.png
    - packages/sbp/assets/icons/hakasskii.png
    - packages/sbp/assets/icons/hlynov.png
    - packages/sbp/assets/icons/homecredit.png
    - packages/sbp/assets/icons/kebr.png
    - packages/sbp/assets/icons/kubankredit.png
    - packages/sbp/assets/icons/letobank.png
    - packages/sbp/assets/icons/levoberezhny.png
    - packages/sbp/assets/icons/mkb.png
    - packages/sbp/assets/icons/mosoblbank.png
    - packages/sbp/assets/icons/mts.png
    - packages/sbp/assets/icons/novikom.png
    - packages/sbp/assets/icons/openbank.png
    - packages/sbp/assets/icons/otpbank.png
    - packages/sbp/assets/icons/pcb.png
    - packages/sbp/assets/icons/pskb.png
    - packages/sbp/assets/icons/qivi.png
    - packages/sbp/assets/icons/raiffeisen.png
    - packages/sbp/assets/icons/rc.png
    - packages/sbp/assets/icons/rncb.png
    - packages/sbp/assets/icons/rosbank.png
    - packages/sbp/assets/icons/roscap.png
    - packages/sbp/assets/icons/rostfb.png
    - packages/sbp/assets/icons/rshb.png
    - packages/sbp/assets/icons/sber.png
    - packages/sbp/assets/icons/sinara.png
    - packages/sbp/assets/icons/smp.png
    - packages/sbp/assets/icons/solidarnost.png
    - packages/sbp/assets/icons/sovcomcard.png
    - packages/sbp/assets/icons/tinkoff.png
    - packages/sbp/assets/icons/tkbbank.png
    - packages/sbp/assets/icons/ucb.png
    - packages/sbp/assets/icons/vbrr.png
    - packages/sbp/assets/icons/vtb.png
    - packages/sbp/assets/icons/ybrir.png
    - packages/sbp/assets/icons/zenit.png
    - packages/sbp/assets/source/absolut.webp
    - packages/sbp/assets/source/akbars.webp
    - packages/sbp/assets/source/alfabank.png
    - packages/sbp/assets/source/artsofte.png
    - packages/sbp/assets/source/avangard.webp
    - packages/sbp/assets/source/bankuralsib.webp
    - packages/sbp/assets/source/bbr.webp
    - packages/sbp/assets/source/blanc.webp
    - packages/sbp/assets/source/brs.webp
    - packages/sbp/assets/source/bspb.webp
    - packages/sbp/assets/source/centrinvest.webp
    - packages/sbp/assets/source/elplat.webp
    - packages/sbp/assets/source/expobank.webp
    - packages/sbp/assets/source/factura.webp
    - packages/sbp/assets/source/gazprombank.jpg
    - packages/sbp/assets/source/gebank.webp
    - packages/sbp/assets/source/hakasskii.webp
    - packages/sbp/assets/source/hlynov.webp
    - packages/sbp/assets/source/homecredit.webp
    - packages/sbp/assets/source/kebr.webp
    - packages/sbp/assets/source/kubankredit.webp
    - packages/sbp/assets/source/letobank.png
    - packages/sbp/assets/source/levoberezhny.webp
    - packages/sbp/assets/source/mkb.jpg
    - packages/sbp/assets/source/mosoblbank.png
    - packages/sbp/assets/source/mts.png
    - packages/sbp/assets/source/novikom.png
    - packages/sbp/assets/source/openbank.png
    - packages/sbp/assets/source/otpbank.webp
    - packages/sbp/assets/source/pcb.png
    - packages/sbp/assets/source/pskb.webp
    - packages/sbp/assets/source/qivi.webp
    - packages/sbp/assets/source/raiffeisen.webp
    - packages/sbp/assets/source/rc.webp
    - packages/sbp/assets/source/rncb.png
    - packages/sbp/assets/source/rosbank.png
    - packages/sbp/assets/source/roscap.png
    - packages/sbp/assets/source/rostfb.webp
    - packages/sbp/assets/source/rshb.png
    - packages/sbp/assets/source/sber.png
    - packages/sbp/assets/source/sinara.webp
    - packages/sbp/assets/source/smp.jpg
    - packages/sbp/assets/source/solidarnost.webp
    - packages/sbp/assets/source/sovcomcard.png
    - packages/sbp/assets/source/tinkoff.webp
    - packages/sbp/assets/source/tkbbank.png
    - packages/sbp/assets/source/ucb.webp
    - packages/sbp/assets/source/vbrr.webp
    - packages/sbp/assets/source/vtb.png
    - packages/sbp/assets/source/ybrir.jpg
    - packages/sbp/assets/source/zenit.webp
    - packages/sbp/assets/source_png/absolut.png
    - packages/sbp/assets/source_png/akbars.png
    - packages/sbp/assets/source_png/alfabank.png
    - packages/sbp/assets/source_png/artsofte.png
    - packages/sbp/assets/source_png/avangard.png
    - packages/sbp/assets/source_png/bankuralsib.png
    - packages/sbp/assets/source_png/bbr.png
    - packages/sbp/assets/source_png/blanc.png
    - packages/sbp/assets/source_png/brs.png
    - packages/sbp/assets/source_png/bspb.png
    - packages/sbp/assets/source_png/centrinvest.png
    - packages/sbp/assets/source_png/elplat.png
    - packages/sbp/assets/source_png/expobank.png
    - packages/sbp/assets/source_png/factura.png
    - packages/sbp/assets/source_png/gazprombank.png
    - packages/sbp/assets/source_png/gebank.png
    - packages/sbp/assets/source_png/hakasskii.png
    - packages/sbp/assets/source_png/hlynov.png
    - packages/sbp/assets/source_png/homecredit.png
    - packages/sbp/assets/source_png/kebr.png
    - packages/sbp/assets/source_png/kubankredit.png
    - packages/sbp/assets/source_png/letobank.png
    - packages/sbp/assets/source_png/levoberezhny.png
    - packages/sbp/assets/source_png/mkb.png
    - packages/sbp/assets/source_png/mosoblbank.png
    - packages/sbp/assets/source_png/mts.png
    - packages/sbp/assets/source_png/novikom.png
    - packages/sbp/assets/source_png/openbank.png
    - packages/sbp/assets/source_png/otpbank.png
    - packages/sbp/assets/source_png/pcb.png
    - packages/sbp/assets/source_png/pskb.png
    - packages/sbp/assets/source_png/qivi.png
    - packages/sbp/assets/source_png/raiffeisen.png
    - packages/sbp/assets/source_png/rc.png
    - packages/sbp/assets/source_png/rncb.png
    - packages/sbp/assets/source_png/rosbank.png
    - packages/sbp/assets/source_png/roscap.png
    - packages/sbp/assets/source_png/rostfb.png
    - packages/sbp/assets/source_png/rshb.png
    - packages/sbp/assets/source_png/sber.png
    - packages/sbp/assets/source_png/sinara.png
    - packages/sbp/assets/source_png/smp.png
    - packages/sbp/assets/source_png/solidarnost.png
    - packages/sbp/assets/source_png/sovcomcard.png
    - packages/sbp/assets/source_png/tinkoff.png
    - packages/sbp/assets/source_png/tkbbank.png
    - packages/sbp/assets/source_png/ucb.png
    - packages/sbp/assets/source_png/vbrr.png
    - packages/sbp/assets/source_png/vtb.png
    - packages/sbp/assets/source_png/ybrir.png
    - packages/sbp/assets/source_png/zenit.png

  uses-material-design: true
