name: sbp
description: Flutter plugin, with which you can get a list of banks installed on the user's device, as well as launch a link to pay via SBP like https://qr.nspk.ru/.../
version: 0.0.9
repository: https://github.com/smenateam/sbp/tree/master/lib
homepage: https://github.com/smenateam/sbp

environment:
  sdk: '>=2.16.1 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.sbp
        pluginClass: SbpPlugin
      ios:
        pluginClass: SbpPlugin
